name: Gitbub-action-practice

on:
  push:
    branches: [ our-first-pipeline ]
    paths:
     - 'factorial.py'
     - 'lint_test.py'
     
job:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Test which OS is the runner using
       run: echo "This job is now running on ${{ runner.os }} server hosted by GitHub!"
     - name: Which branch is checked out
       run: echo "The name of the branch is ${{ github.ref }} in repository ${{ github.repository }}"
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.9
     - name: Install dependencies 
       run: | 
          python- m pip install --upgrade pip
          pip install pylint
     - name: Lint with pylint
       run: |
         python lint_test.py
     - name: Build container
       run: 
         echo "Building docker container..."
         sleep 60 
         echo "Docker container built succesfully"
     - name: Deploy 
        run: | 
          echo "Deploying to imaginary cluster"
          sleep 60
          echo "App has been deployed successfully" 
       - run: echo "This job's status is ${{ job.status }}."
